routes/web.php
<?php

use App\Http\Controllers\NoteController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\TrashedNoteController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    Route::resource('notes', NoteController::class);

    Route::prefix('/trashed')->name('trashed.')->group(function () {
        Route::get('/', [TrashedNoteController::class, 'index'])->name('index');
        Route::get('/{note}', [TrashedNoteController::class, 'show'])->name('show')->withTrashed();
        Route::put('/{note}', [TrashedNoteController::class, 'update'])->name('update')->withTrashed();
        Route::delete('/{note}', [TrashedNoteController::class, 'destroy'])->name('destroy')->withTrashed();
    });

//    Route::get('/trashed', [TrashedNoteController::class, 'index'])
//        ->name('trashed.index');
//    Route::get('/trashed/{note}', [TrashedNoteController::class, 'show'])
//        ->withTrashed()
//        ->name('trashed.show');
//    Route::put('/trashed/{note}', [TrashedNoteController::class, 'update'])
//        ->withTrashed()
//        ->name('trashed.update');
//    Route::delete('/trashed/{note}', [TrashedNoteController::class, 'destroy'])
//        ->withTrashed()
//        ->name('trashed.destroy');
});

require __DIR__.'/auth.php';

app/Models/Note.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;

class Note extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $guarded = [];

//    protected $fillable = ['user_id', 'title', 'text'];

    public function getRouteKeyName(): string
    {
        return 'uuid';
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/NoteController.php
<?php

namespace App\Http\Controllers;

use App\Models\Note;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;
use Illuminate\View\View;

class NoteController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(): View
    {
//        $notes = Note::query()
//            ->where(['user_id' => Auth::id()])
//            ->latest('updated_at')
//            ->paginate(5);

//        $notes = Auth::user()
//            ->notes()
//            ->latest('updated_at')
//            ->paginate(5);

        $notes = Note::query()
            ->whereBelongsTo(Auth::user())
            ->latest('updated_at')
            ->paginate(5);

        return view('notes.index')->with('notes', $notes);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create(): View
    {
        return view('notes.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request): RedirectResponse
    {
        $request->validate([
            'title' => ['required', 'max:120'],
            'text' => ['required']
        ]);

//        Note::query()
//            ->create([
//                'uuid' => Str::uuid(),
//                'user_id' => Auth::id(),
//                'title' => $request->get('title'),
//                'text' => $request->get('text'),
//            ]);

        Auth::user()
            ->notes()
            ->create([
                'uuid' => Str::uuid(),
                'title' => $request->get('title'),
                'text' => $request->get('text'),
            ]);

        return to_route('notes.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(Note $note): View
    {
//        return $note['user_id'] !== Auth::id() ? abort(403) : view('notes.show')->with('note', $note);
        return $note->user->is(Auth::user()) ? view('notes.show')->with('note', $note) : abort(403);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Note $note): View
    {
        return $note['user_id'] !== Auth::id() ? abort(403) : view('notes.edit')->with('note', $note);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Note $note): RedirectResponse
    {
        $request->validate([
            'title' => ['required', 'max:120'],
            'text' => ['required']
        ]);

        if (!$note->user->is(Auth::user())) abort(403);

        $note->update([
            'title' => $request->get('title'),
            'text' => $request->get('text'),
        ]);

        return to_route('notes.show', $note)->with('success', 'Note updates successfully');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Note $note): RedirectResponse
    {
        if (!$note->user->is(Auth::user())) abort(403);

        $note->delete();

        return to_route('notes.index')->with('success', 'Note moved to trash');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/notes/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Notes') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="my-6 p-6 bg-white border-b border-gray-200 shadow-sm sm:rounded-lg">
                <form action="{{ route('notes.store') }}" method="post">
                    @csrf
                    <label>
                        <x-text-input
                            type="text"
                            name="title"
                            field="title"
                            placeholder="Title"
                            class="w-full"
                            autocomplete="off"
                            :value="@old('title')"></x-text-input>
                    </label>
                    <label>
                        <x-textarea
                            name="text"
                            field="text"
                            rows="10"
                            placeholder="Start typing here..."
                            class="w-full mt-6"
                            :value="@old('text')"></x-textarea>
                    </label>
                    <x-primary-button class="mt-6">Save Note</x-primary-button>
                </form>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/notes/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Edit Note') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="my-6 p-6 bg-white border-b border-gray-200 shadow-sm sm:rounded-lg">
                <form action="{{ route('notes.update', $note) }}" method="post">
                    @method('put')
                    @csrf
                    <label>
                        <x-text-input
                            type="text"
                            name="title"
                            field="title"
                            placeholder="Title"
                            class="w-full"
                            autocomplete="off"
                            :value="@old('title', $note->title)"></x-text-input>
                    </label>
                    <label>
                        <x-textarea
                            name="text"
                            field="text"
                            rows="10"
                            placeholder="Start typing here..."
                            class="w-full mt-6"
                            :value="@old('text', $note->text)"></x-textarea>
                    </label>
                    <x-primary-button class="mt-6">Save Note</x-primary-button>
                </form>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/notes/index.blade.php
@php use Illuminate\Support\Str; @endphp
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ request()->routeIs('notes.index') ? __('Notes') : __('Trash') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <x-alert-success>
                {{ session('success') }}
            </x-alert-success>

            @if(request()->routeIs('notes.index'))
                <a href="{{ route('notes.create') }}" class="btn-link btn-lg mb-2">+ New Note</a>
            @endif

            @forelse($notes as $note)
                <div class="my-6 p-6 bg-white border-b border-gray-200 shadow-sm sm:rounded-lg">
                    <h2 class="font-bold text-2xl">
                        <a href="{{ request()->routeIs('notes.index')
                            ? route('notes.show', $note)
                            : route('trashed.show', $note)
                        }}">{{ $note->title }}</a>
                    </h2>
                    <p class="mt-2">
                        {{ Str::limit($note->text, 200) }}
                    </p>
                    <span class="block mt-4 text-sm opacity-70">{{ $note->updated_at->diffForHumans() }}</span>
                </div>
            @empty
                <div class="my-6 p-6 bg-white border-b border-gray-200 shadow-sm sm:rounded-lg">
                    @if(request()->routeIs('notes.index'))
                        <p>You have no notes yet.</p>
                    @else
                        <p>No items in the trash.</p>
                    @endif
                </div>
            @endforelse
            {{ $notes->links() }}
        </div>
    </div>
</x-app-layout>

resources/views/notes/show.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ $note->trashed() ? __('Trash') : __('Notes') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <x-alert-success>
                {{ session('success') }}
            </x-alert-success>
            <div class="flex">
                @if($note->trashed())
                    <p class="opacity-70">
                        <strong>Deleted: </strong> {{ $note->deleted_at->diffForHumans() }}
                    </p>
                    <form action="{{ route('trashed.update', $note) }}" method="post" class="ml-auto">
                        @method('put')
                        @csrf
                        <button type="submit" class="btn-link">Restore Note</button>
                    </form>
                    <form action="{{ route('trashed.destroy', $note) }}" method="post">
                        @method('delete')
                        @csrf
                        <button type="submit" class="btn btn-danger ml-4"
                                onclick="return confirm('Are you sure you wish to delete this note forever?')">Delete Forever
                        </button>
                    </form>
                @else
                    <p class="opacity-70">
                        <strong>Created: </strong> {{ $note->created_at->diffForHumans() }}
                    </p>
                    <p class="opacity-70 ml-8">
                        <strong>Updated: </strong> {{ $note->updated_at->diffForHumans() }}
                    </p>
                    <a href="{{ route('notes.edit', $note) }}" class="btn-link ml-auto">Edit Note</a>
                    <form action="{{ route('notes.destroy', $note) }}" method="post">
                        @method('delete')
                        @csrf
                        <button type="submit" class="btn btn-danger ml-4"
                                onclick="return confirm('Are you sure you wish to delete this to trash?')">Move to Trash
                        </button>
                    </form>
                @endif
            </div>
            <div class="my-6 p-6 bg-white border-b border-gray-200 shadow-sm sm:rounded-lg">
                <h2 class="font-bold text-5xl">
                    {{ $note->title }}
                </h2>
                <p class="mt-8 whitespace-pre-wrap">{{ $note->text }}</p>
            </div>
        </div>
    </div>
</x-app-layout>